#!/bin/bash
# Codi Gripspace Environment Setup
#
# Source this file to set up your environment:
#   source ./envsetup.sh
#
# This adds shell functions for common development tasks.
# Also generates .codi-env for AI tools to read.

# Get the directory where this script lives
# Handle both bash and zsh
if [[ -n "$BASH_SOURCE" ]]; then
    CODI_WORKSPACE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
elif [[ -n "$ZSH_VERSION" ]]; then
    CODI_WORKSPACE="$(cd "$(dirname "${(%):-%x}")" && pwd)"
else
    # Fallback - assume script is in current directory
    CODI_WORKSPACE="$(pwd)"
fi

# ============================================
# Environment Variables
# ============================================

export CODI_WORKSPACE
export CODI_SRC="$CODI_WORKSPACE/codi"
export CODI_RS_SRC="$CODI_WORKSPACE/codi/codi-rs"
# Use workspace-local .codi for sessions, data, etc.
export CODI_HOME="$CODI_WORKSPACE/.codi"

# ============================================
# Generate .codi-env (for AI tools to read)
# ============================================

cat > "$CODI_WORKSPACE/.codi-env" << EOF
# Auto-generated by envsetup.sh - do not edit manually
# This file is read by AI tools to understand the workspace paths
CODI_WORKSPACE=$CODI_WORKSPACE
CODI_SRC=$CODI_SRC
CODI_RS_SRC=$CODI_RS_SRC
CODI_HOME=$CODI_HOME
EOF

# ============================================
# Shell Functions - TypeScript
# ============================================

# Run codi TypeScript in dev mode
function codi-dev() {
    (cd "$CODI_SRC" && CODI_HOME="$CODI_HOME" pnpm dev "$@")
}

# Build codi TypeScript
function codi-build() {
    echo "Building codi (TypeScript)..."
    (cd "$CODI_SRC" && pnpm build) && \
    echo "Build complete!"
}

# Run codi TypeScript tests
function codi-test() {
    (cd "$CODI_SRC" && pnpm test "$@")
}

# ============================================
# Shell Functions - Rust
# ============================================

# Run codi Rust
function codi-dev-rs() {
    (cd "$CODI_RS_SRC" && cargo run "$@")
}

# Build codi Rust
function codi-build-rs() {
    echo "Building codi (Rust)..."
    (cd "$CODI_RS_SRC" && cargo build) && \
    echo "Build complete!"
}

# Run codi Rust tests
function codi-test-rs() {
    (cd "$CODI_RS_SRC" && cargo test "$@")
}

# ============================================
# Shell Functions - Combined
# ============================================

# Build both TypeScript and Rust
function codi-build-all() {
    echo "Building codi (TypeScript)..."
    (cd "$CODI_SRC" && pnpm build) && \
    echo "Building codi (Rust)..." && \
    (cd "$CODI_RS_SRC" && cargo build) && \
    echo "All builds complete!"
}

# ============================================
# Navigation
# ============================================

# Quick cd to codi TypeScript directory
function cdc() {
    cd "$CODI_SRC"
}

# Quick cd to codi Rust directory
function cdcr() {
    cd "$CODI_RS_SRC"
}

# Quick cd to gitgrip directory
function cdg() {
    cd "$CODI_WORKSPACE/gitgrip"
}

# Quick cd to workspace root
function cdw() {
    cd "$CODI_WORKSPACE"
}

# ============================================
# Help
# ============================================

function codi-help() {
    cat << 'EOF'
Codi Gripspace Commands:

  TypeScript:
    codi-dev [args]       Run codi TypeScript in dev mode
    codi-build            Build codi TypeScript
    codi-test [args]      Run codi TypeScript tests

  Rust:
    codi-dev-rs [args]    Run codi Rust (cargo run)
    codi-build-rs         Build codi Rust
    codi-test-rs [args]   Run codi Rust tests

  Both:
    codi-build-all        Build TypeScript + Rust

  Navigation:
    cdc                   cd to codi/ (TypeScript)
    cdcr                  cd to codi/codi-rs/ (Rust)
    cdg                   cd to gitgrip/
    cdw                   cd to workspace root

  gitgrip scripts (gr run):
    gr run --list         Show all scripts
    gr run build-all      Build everything
    gr run test-all       Run all tests

  Post-merge checklist:
    gr checkout --base    Return to base branch
    gr sync               Pull latest upstream
    gr prune              Preview merged branch cleanup
    gr prune --execute    Delete merged branches

  Help:
    codi-help             Show this help message

  Environment:
    CODI_WORKSPACE        Workspace root
    CODI_SRC              Codi TypeScript source (./codi)
    CODI_RS_SRC           Codi Rust source (./codi/codi-rs)
    CODI_HOME             Local .codi directory
EOF
}

# ============================================
# Completion (optional)
# ============================================

if [[ -n "$BASH_VERSION" ]]; then
    complete -F _command codi-dev
    complete -F _command codi-dev-rs
fi

# ============================================
# Startup Message
# ============================================

echo "Codi gripspace initialized!"
echo "  CODI_WORKSPACE=$CODI_WORKSPACE"
echo ""
echo "Run 'codi-help' to see available commands."
